CLASS zust01_cl_bop DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun .
    INTERFACES if_rap_query_provider.
    METHODS: BOP_FORCE_CONFIRMATION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZUST01_CL_BOP IMPLEMENTATION.


  METHOD if_rap_query_provider~select.
    BOP_FORCE_CONFIRMATION( ).
  ENDMETHOD.


  METHOD if_oo_adt_classrun~main.

    BOP_FORCE_CONFIRMATION( ).
  ENDMETHOD.


  METHOD BOP_FORCE_CONFIRMATION.

  ENDMETHOD.
ENDCLASS.
